### ISSUE TITLE
bug (?): with NERDtree open, files are always opened in the left/top most split 

### ISSUE THREAD

**Issue by svanharmelen** [ctrlpvim/ctrlp.vim#235]
When I open a file found with CtrlP by pressing <CR>, it always opens in the left/top most split regardless of the split I was in when pressing <c-p> when I also have NERDtree open.

But when I toggle to close the NERDtree window and try it again, files are properly opened in the split I was in when pressing <c-p>.

Is this a bug or can this be fixed by tweaking some settings? Did already look at the options and googled some, but couldn't find a solution...

**Comment by gregflynn** [comment]
Confirmed, seeing the same behavior

**Comment by mattn** [comment]
I don't see this behavior with NERDTree. Could you please explain how to reproduce?

**Comment by svanharmelen** [comment]
@mattn see the following two screen captures... 

The first one is showing that with NERDtree open, using CtrlP from the right split it will always open the file in the top/left split instead of in the split that I was in when pressing `<C-p>`:
![with2](https://cloud.githubusercontent.com/assets/4171547/15206292/556b1246-181e-11e6-8d08-72aba3cb479a.gif)

The second one shows the same action (using CtrlP from the right split) but now without NERDtree open which then has the expected behaviour (the file is opened in the split I was in when pressing `<C-p>`:
![without](https://cloud.githubusercontent.com/assets/4171547/15206256/0b6e6698-181e-11e6-8765-d6911376dea8.gif)

Does this help to understand and reproduce?

**Comment by mattn** [comment]
CtrlP open the selected buffer in last focused buffer. But selected buffer is located in another buffer, open the buffer with moving focus. Sorry, I can't see too small fonts, so I can't confirm the buffer name. Could you please test with small example.

```
$ mkdir example
$ echo 'This is buffer "a"' > a
$ echo 'This is buffer "b"' > b
$ echo 'This is buffer "c"' > c
$ vim a
```

```
:rightbelow vsp b
```
move left side pane, then CtrlP.

**Comment by svanharmelen** [comment]
Strangely enough I do have issues trying to consistently reproduce this with just 3 example files 😞 

To do more testing (and maybe as a solution to my experience), is there an option that makes CtrlP open the selected buffer in the last focussed buffer, even when the selected buffer is already open, but hidden, in another buffer? I searched for that, but could not find the answer...

**Comment by gregflynn** [comment]
> mkdir test
> echo "AAA" > test/a.txt
> echo "BBB" > test/b.txt
> cd test && vim

Once vim is open:
> :NerdTreeToggle
> Ctrl+w Ctrl+w to focus the code pane
> :vsp
> Ctrl+w Ctrl+w to focus the new pane
<c-p>a.txt

"AAA" will be shown in the left pane instead of the right pane

**Comment by marklawlor** [comment]
Commit 9763bb8bc47d2731a7c67925ccef4a554e54b9a4 is causing this issue for me.

A quick work around is checking out ctrlp.vim to the previous commit f6c587e408dc0b45ffbabdadbb19739f8429e1eb

**Comment by mattn** [comment]
@qstrahl do you have opinion?

**Comment by svanharmelen** [comment]
@marklawlor I don't think this is the same issue, but commit https://github.com/ctrlpvim/ctrlp.vim/commit/f6c587e408dc0b45ffbabdadbb19739f8429e1eb in indeed also causing issues for me. This commit makes a new buffer open inside the NERDtree window, which is actually worse as it was before...

**Comment by prabirshrestha** [comment]
I'm also seeing the same behavior.

**Comment by brodock** [comment]
same behavior as @svanharmelen

**Comment by mattn** [comment]
if you all are okay with  reverting https://github.com/ctrlpvim/ctrlp.vim/commit/f6c587e408dc0b45ffbabdadbb19739f8429e1eb, I will do it.

**Comment by svanharmelen** [comment]
@mattn it will not solve this issue completely, but that commit certainly makes things even worse (from always selecting the left-top window to selecting the NERTree window), so I would say rolling back that one is a step in the right direction...

**Comment by mattn** [comment]
reverted

**Comment by sprt** [comment]
CtrlP randomly opens files in the NERDTree pane for me. Like @marklawlor, I found that the bug was introduced by commit 9763bb8. [Reverting the commit](https://github.com/sprt/ctrlp.vim-nerdtree-fix/commit/eced4a0773df35fbc562161fea59163c171a7435) fixed the issue for me.

**Comment by svanharmelen** [comment]
@mattn I'm really sorry, but indeed we made an error here. It's not commit f6c587e that was causing the additional problems, but the commit right after that: 9763bb8 (so reverting **back to** f6c587e fixes it, but just reverting f6c587e itself does not 😞 )

Could you fix this or should I send in a PR to undo the revert of f6c587e and revert 9763bb8 instead? Please let me know so we at least can solve half of this issue.

Once that part is done, I will try to invest some time to get the rest fixed as well... Thx!

**Comment by mattn** [comment]
Thanks for your look. Please send me fix.

**Comment by svanharmelen** [comment]
@sprt @marklawlor @gregflynn do you guys by any change use `nerdtree-git-plugin`? As I think I found the root cause (at least for my issues I can now clearly show and fix the issue) to be in that plugin.

So please let me know if you also use `nerdtree-git-plugin` as that would confirm my findings and I can put in a PR with the fix.

**Comment by gregflynn** [comment]
@svanharmelen Yup!

> Plugin 'scrooloose/nerdTree'
> Plugin 'Xuyuanp/nerdtree-git-plugin'

**Comment by marklawlor** [comment]
@svanharmelen No but I used ryanoasis/vim-devicons which seems to modify Nerdtree in a similar manner

**Comment by svanharmelen** [comment]
@marklawlor yes, I found the exact same lines in that plugin as well... Thx!

**Comment by svanharmelen** [comment]
@mattn could you give me some advice? I found the problem and through it seems questionable if we should fix it in `CtrlP`, I think it would be the best and most robust way to fix the problem.

The issue is caused by at least two different plugins that use the same kind of logic to update a window, the NERDTree window in this case.

Please see this code snipped:

```
    let l:winnr = winnr()
    call g:NERDTree.CursorToTreeWin()
    call b:NERDTree.root.refreshFlags()
    call NERDTreeRender()
    exec l:winnr . 'wincmd w'
```

As you can see it switches to the NERDTree window and the back again to the window where it came from (the `CtrlP` window). One way to fix it, is by updating the code in the different plugins so it looks like this:

```
    let l:winnr = winnr()
    let l:altwinnr = winnr('#')
    call g:NERDTree.CursorToTreeWin()
    call b:NERDTree.root.refreshFlags()
    call NERDTreeRender()
    exec l:altwinnr . 'wincmd w'
    exec l:winnr . 'wincmd w'
```

So now it also resets the alternate window and this seems to solve the problem. Now I can make PR's for the plugins I know that use this logic (at least 2 that I know of), or we can try to solve the problem once in this package. This will make `CtrlP` more robust and not dependent from what other plugins do. Next to that the additional selection of the alternate window causes some visual effects (scrolling) if you have something like `set scrolloff=999` in your vimrc, which feels kind of wrong...

So my current reasoning is that `CtrlP` is somewhere/somehow using the alternate window number as input for some internal function or as part of the cmd to actually open the selected file.

So if we could save the alternate window number to a local variable right when opening the `CtrlP` window, and then use that variable later on when it would otherwise use the alternate window number, that would solve the problem very nicely.

Now I did look at the code, but I must say I find it rather hard to read. I did some small VimL things before, but this is written in a way that it poses a challenge for me to find the right location and/or to verify my reasoning.

So if you could help me along a little by both verifying my reasoning and by pointing me in the right direction as to what part of the code is related to this, that would be great. Of course if you can already see/know the solution itself with this additional info, that would of course be even better :wink:

Hope you can find some time to help me fix this as I feel we are so very, very close now 😁 

Thx!

**Comment by mattn** [comment]
I guess this need to fixes for CtrlP to solve this issue.

1. Correct last current window when closing CtrlP. I merged this fix into master https://github.com/ctrlpvim/ctrlp.vim/pull/302 just now

2. You can put configuration to find free window to open buffer like below.

```vim
function! CtrlP_OpenAtCenter(...)
  " find free window
  for n in range(0, bufnr('$'))
    if buflisted(n)
      exe bufwinnr(n) . 'wincmd w'
      break
    endif
  endfor
  call call('ctrlp#acceptfile', a:000)
endfunction

let g:ctrlp_open_func = {
\  'arg_type': 'dict',
\  'files': 'CtrlP_OpenAtCenter',
\}
```

**Comment by svanharmelen** [comment]
Thank you very much for your help, but unfortunately this patch doesn't fix the problem.

You did however point me in the right, so I found a way to fix this in `CtrlP`. Will create a PR for the hack in a few minutes so you can see what I did to fix it.

I say "hack" because I doubt this is the proper way to fix it, but maybe it will give more insights and background which will hopefully leads to a proper solution.

**Comment by svanharmelen** [comment]
@mattn see the last commit of PR #303 to see the hack/fix I'm talking about... Thx!

**Comment by svanharmelen** [comment]
@gregflynn this should now be fixed by https://github.com/Xuyuanp/nerdtree-git-plugin/issues/63 which is merged just now 🎉

**Comment by mboughaba** [comment]
This is still not fixed.
I have to use the hack below to make it work
```vimscript
function! CtrlPCommand()
    let c = 0
    let wincount = winnr('$')
    " Don't open it here if current buffer is not writable (e.g. NERDTree)
    while !empty(getbufvar(+expand("<abuf>"), "&buftype")) && c < wincount
        exec 'wincmd w'
        let c = c + 1
    endwhile
    exec 'CtrlP'
endfunction
let g:ctrlp_cmd = 'call CtrlPCommand()'
```
I didn't come up with this hack myself, I found it in a comment in the upstream *sorry for not adding reference to that comment :(*
I think this can make a more robust fix for long term as we don't check a specific plugin but instead if buffer is writable.

I will be glad to make a PR for that if fine for everyone.
Cheers
