### ISSUE TITLE
unexpected behaviour of CtrlPBuffer with ctrlp_by_filename

### ISSUE THREAD

**Issue by ambushed** [ctrlpvim/ctrlp.vim#346]
Hi!

I have the following lines in my .vimrc:

> let g:ctrlp_cmd = 'CtrlPBuffer'                                                                                                                                                               
> let g:ctrlp_no_caching = 1                                                                                                                                                                     
> let g:ctrlp_by_filename = 1  

I expect the default <C-p> stroke to default to searching by (only) filename in buffers, yet, as I type, the matching substrings in folder column are being highlighted and the best match doesn't correspond to the filename-only substring.

What am i missing?

Thanks

**Comment by tacahiroy** [comment]
You're right. I'll try to fix this

**Comment by tacahiroy** [comment]
I've fixed the matching problem in this branch, highlighting is incorrect though.
Wrt highlighting thing, seems to be incorrect since this buffer mode changes introduced.
https://github.com/ctrlpvim/ctrlp.vim/tree/fix-buf-matching-by-fname

**Comment by ambushed** [comment]
I confirm that the fix works!  Thanks!  But, as you say, highlighting still doesn't.

**Comment by tacahiroy** [comment]
Thanks for your confirmation. I'll merge the branch into master.
WRT highlighting thing, it's better to be a separate issue.

**Comment by tacahiroy** [comment]
have merged my changes into master. closing this.
